name: newbie_project
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  core:
    path: ./modules/core
  auth:
    path: ./modules/auth
  product:
    path: ./modules/product

  #Ui
  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.4.1

  get: ^4.6.6

  #state_management
  flutter_bloc: ^8.1.6

  #network
  dio: ^5.7.0

  #build
  build_runner: ^2.4.12

  freezed_annotation: ^2.2.0

  #lint
  flutter_gen: ^5.7.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  melos: ^6.1.0

flutter:
  generate: true
  uses-material-design: true
