name: product
description: "A new Flutter module project."

version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  auth:
    path: ../auth

  #route
  auto_route: ^9.2.2

  #build
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

  #model
  injectable: ^2.4.4
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0

  #reactive
  reactive_forms_annotations: ^5.0.0
  reactive_forms: ^17.0.1
  reactive_forms_generator: ^5.0.5

  #network
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0
  dio: ^5.7.0

  #state_management
  flutter_bloc: ^8.1.6

  #instance
  get_it: ^7.7.0

  #ui
  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  gradient_elevated_button: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.product
    iosBundleIdentifier: com.example.product
