name: core
description: "A new Flutter module project."

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #DI
  get: ^4.6.6
  get_it: ^7.7.0
  injectable: ^2.4.4
  injectable_generator: ^2.6.2

  #Network
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  flutter_dotenv: ^5.1.0

  #structure
  intl: ^0.19.0
  tuple: ^2.0.2
  flutter_lints: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.core
    iosBundleIdentifier: com.example.core
